# Site settings
title: null
name: Coletivo Amígdalas
description: >
  Agenda de Curso, Apresentações, Notícias e Eventos do Coletivo Amígdalas.
baseurl: "/coletivoamigdalas" # the subpath of your site, e.g. /blog/
url: "https://jetrotal.github.io" # the base hostname & protocol for your site
data-theme: dark
